// SPDX-FileCopyrightText: 2023 Väinö Mäkelä <vaino.makela@iki.fi>
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Handler for Varlink requests

const std = @import("std");
const orgVarlinkService = @import("orgVarlinkService");

pub const Options = packed struct {
    oneway: bool = false,
    more: bool = false,
    upgrade: bool = false,
};

fn isHashMap(comptime T: type) bool {
    if (comptime @typeInfo(T) == .Struct) {
        // Custom types generated by our scanner don't have any
        // user-controllable declarations, so this should not report false
        // positives.
        return @hasDecl(T, "KV");
    }
    return false;
}

const JsonParsingError = std.mem.Allocator.Error || error{InvalidParameter};

fn parseToStruct(
    comptime T: type,
    allocator: std.mem.Allocator,
    json: std.json.Value,
    invalid_parameter: *?[]const u8,
) JsonParsingError!T {
    const struc = switch (@typeInfo(T)) {
        .Struct => |struc| struc,
        else => @compileError("Expected a struct, got: " ++ @typeName(T)),
    };
    const map: std.json.ObjectMap = blk: {
        switch (json) {
            .object => |map| break :blk map,
            else => return error.InvalidParameter,
        }
    };
    if (comptime isHashMap(T)) {
        var result: T = .{};
        var it = map.iterator();
        while (it.next()) |entry| {
            try result.putNoClobber(
                allocator,
                entry.key_ptr.*,
                try parseToType(
                    std.meta.fieldInfo(T.KV, .value).type,
                    allocator,
                    entry.value_ptr.*,
                ),
            );
        }
        return result;
    }
    var result: T = undefined;
    inline for (struc.fields) |field| {
        if (map.get(field.name)) |value| {
            invalid_parameter.* = field.name;
            @field(result, field.name) = try parseToType(
                field.type,
                allocator,
                value,
            );
        } else if (@typeInfo(field.type) == .Optional) {
            @field(result, field.name) = null;
        } else {
            invalid_parameter.* = field.name;
            return error.InvalidParameter;
        }
    }
    return result;
}

fn parseToType(
    comptime T: type,
    allocator: std.mem.Allocator,
    json: std.json.Value,
) JsonParsingError!T {
    if (T == std.json.Value) {
        return json;
    }
    switch (@typeInfo(T)) {
        .Bool => {
            switch (json) {
                .bool => |b| return b,
                else => return error.InvalidParameter,
            }
        },
        .Int => {
            switch (json) {
                .integer => |i| return i,
                else => return error.InvalidParameter,
            }
        },
        .Float => {
            switch (json) {
                .float => |f| return f,
                else => return error.InvalidParameter,
            }
        },
        .Pointer => |pointer| {
            if (pointer.size != .Slice) {
                @compileError("Expected a slice");
            }
            // The scanner always uses i64 as the integer type, so there is no
            // possibility of confusing strings with arrays of integers.
            if (pointer.child == u8) {
                switch (json) {
                    .string => |s| return s,
                    else => return error.InvalidParameter,
                }
            } else {
                switch (json) {
                    .array => |arr| {
                        // Exact memory management is not needed here as we are
                        // using an arena allocator.
                        const result = try allocator.alloc(pointer.child, arr.items.len);
                        for (arr.items, 0..) |item, i| {
                            result[i] = try parseToType(
                                pointer.child,
                                allocator,
                                item,
                            );
                        }
                        return result;
                    },
                    else => return error.InvalidParameter,
                }
            }
        },
        .Optional => |optional| {
            switch (json) {
                .null => return null,
                else => return try parseToType(
                    optional.child,
                    allocator,
                    json,
                ),
            }
        },
        .Struct => {
            var dummy_invalid_parameter: ?[]const u8 = null;
            return parseToStruct(T, allocator, json, &dummy_invalid_parameter);
        },
        .Enum => {
            switch (json) {
                .string => |str| return std.meta.stringToEnum(T, str) orelse error.InvalidParameter,
                else => return error.InvalidParameter,
            }
        },
        else => @compileError("Unsupported type: " ++ @typeName(T)),
    }
}

/// Serialize value to std.json.Value. This method does free memory on
/// allocation errors or provide a way to free the allocated memory, so it's
/// recommended to use it with an arena allocator.
pub fn jsonize(value: anytype, allocator: std.mem.Allocator) std.mem.Allocator.Error!std.json.Value {
    const T = @TypeOf(value);
    if (T == std.json.Value) {
        return value;
    }
    if (comptime isHashMap(T)) {
        var result = std.StringArrayHashMap(std.json.Value).init(allocator);
        var it = value.iterator();
        while (it.next()) |entry| {
            try result.putNoClobber(
                entry.key_ptr.*,
                try jsonize(entry.value_ptr.*, allocator),
            );
        }
        return .{ .object = result };
    }
    switch (@typeInfo(T)) {
        .Bool => return .{ .bool = value },
        .Int => return .{ .integer = value },
        .Float => return .{ .float = value },
        .Pointer => |pointer| {
            if (pointer.size == .One) {
                // TODO: Custom compile error for non-string?
                return .{ .string = value };
            }
            if (pointer.size != .Slice) {
                @compileError("Many-item and C pointers are not supported");
            }
            if (pointer.child == u8) {
                return .{ .string = value };
            } else {
                var arr = try std.ArrayList(std.json.Value).initCapacity(
                    allocator,
                    value.len,
                );
                for (value) |element| {
                    arr.appendAssumeCapacity(try jsonize(element, allocator));
                }
                return .{ .array = arr };
            }
        },
        .Optional => {
            if (value) |child| {
                return jsonize(child, allocator);
            } else {
                return .null;
            }
        },
        .Struct => |struc| {
            var result = std.StringArrayHashMap(std.json.Value).init(allocator);
            inline for (struc.fields) |field| {
                try result.putNoClobber(
                    field.name,
                    try jsonize(@field(value, field.name), allocator),
                );
            }
            return .{ .object = result };
        },
        .Enum => return .{ .string = @tagName(value) },
        else => @compileError("Unsupported type: " ++ @typeName(T)),
    }
}

fn writeJson(stream: anytype, json: std.json.Value) !void {
    var write_stream = std.json.writeStream(stream, .{});
    try json.jsonStringify(&write_stream);
}

/// Serialize a Varlink response or error to the given writer. A trailing zero
/// byte is not written to allow usage with transports not using one. This
/// method does not free its allocated memory, so it's recommended to use it
/// with an arena allocator
pub fn serializeResponse(
    stream: anytype,
    response: anytype,
    allocator: std.mem.Allocator,
) !void {
    const ValueType = if (@hasDecl(@TypeOf(response), "error_name")) blk: {
        break :blk struct {
            parameters: @TypeOf(response),
            @"error": []const u8 = @TypeOf(response).error_name,
        };
    } else blk: {
        break :blk struct {
            parameters: @TypeOf(response),
        };
    };

    // TODO: Have a non-allocating implementation
    try writeJson(
        stream,
        try jsonize(
            ValueType{
                .parameters = response,
            },
            allocator,
        ),
    );
}

/// Serialize a Varlink response to the given writer with the "continues" flag
/// set. A trailing zero byte is not written to allow usage with transports not
/// using one. This method does not free its allocated memory, so it's
/// recommended to use it with an arena allocator
pub fn serializeContinueResponse(
    stream: anytype,
    response: anytype,
    allocator: std.mem.Allocator,
) !void {
    try writeJson(
        stream,
        try jsonize(
            .{
                .parameters = response,
                .continues = true,
            },
            allocator,
        ),
    );
}

fn handleMethod(
    method: []const u8,
    parameters: std.json.Value,
    response_stream: anytype,
    allocator: std.mem.Allocator,
    options: Options,
    interface_context: anytype,
    extra_data: anytype,
) !void {
    const Interface = @TypeOf(interface_context.*).interface;
    inline for (@typeInfo(Interface).Struct.decls) |decl| {
        const Request = @field(Interface, decl.name);
        if (@typeInfo(@TypeOf(Request)) != .Type) {
            continue;
        }
        if (!@hasDecl(Request, "Parameters")) {
            continue;
        }
        if (std.mem.eql(u8, decl.name, method)) {
            var invalid_parameter: ?[]const u8 = null;
            const input = parseToStruct(
                Request.Parameters,
                allocator,
                parameters,
                &invalid_parameter,
            ) catch |err| switch (err) {
                error.InvalidParameter => {
                    return serializeResponse(
                        response_stream,
                        orgVarlinkService.InvalidParameter{ .parameter = invalid_parameter.? },
                        allocator,
                    );
                },
                else => return err,
            };
            const request_function = "handle" ++ decl.name;
            if (@hasDecl(@TypeOf(interface_context.*), request_function)) {
                return @call(.auto, @field(
                    @TypeOf(interface_context.*),
                    request_function,
                ), .{
                    interface_context,
                    input,
                    response_stream,
                    allocator,
                    options,
                    extra_data,
                });
            } else {
                return serializeResponse(
                    response_stream,
                    orgVarlinkService.MethodNotImplemented{ .method = method },
                    allocator,
                );
            }
        }
    }
    try serializeResponse(
        response_stream,
        orgVarlinkService.MethodNotFound{ .method = method },
        allocator,
    );
}

fn parseMethod(map: std.json.ObjectMap) error{InvalidMessage}![]const u8 {
    if (map.get("method")) |method_value| {
        switch (method_value) {
            .string => |method_string| return method_string,
            else => return error.InvalidMessage,
        }
    }
    return error.InvalidMessage;
}

fn readOptionValue(json: std.json.Value) error{InvalidMessage}!bool {
    switch (json) {
        .bool => |b| return b,
        .null => return false,
        else => return error.InvalidMessage,
    }
}

fn parseOptions(map: std.json.ObjectMap) error{InvalidMessage}!Options {
    var options: Options = .{};
    if (map.get("oneway")) |oneway_value| {
        options.oneway = try readOptionValue(oneway_value);
    }
    if (map.get("more")) |more_value| {
        options.more = try readOptionValue(more_value);
    }
    if (map.get("upgrade")) |upgrade_value| {
        options.upgrade = try readOptionValue(upgrade_value);
    }
    return options;
}

fn parseParameters(map: std.json.ObjectMap) error{InvalidMessage}!std.json.ObjectMap {
    if (map.get("parameters")) |parameters_value| {
        switch (parameters_value) {
            .object => |parameters_map| {
                return parameters_map;
            },
            else => return error.InvalidMessage,
        }
    } else {
        // libvarlink accepts lacking parameters when they are expected and
        // returns the same error as if the parameters were empty. Let's
        // match this behavior.
        return std.json.ObjectMap.init(undefined);
    }
}

/// Handle a Varlink request.
pub fn handleRequest(
    /// The request string without the trailing zero byte
    request: []const u8,
    /// The writer to which the potential response and errors will be written
    response_stream: anytype,
    /// The allocator to be used by the implementation. All allocations are
    /// always freed before the function returns.
    allocator: std.mem.Allocator,
    /// The context struct that contains request handlers
    context: anytype,
    /// Extra data to give to the request handler
    extra_data: anytype,
) !void {
    const VarlinkService = OrgVarlinkServiceImpl(@TypeOf(context.*));

    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    const json_value = try std.json.parseFromSliceLeaky(
        std.json.Value,
        arena.allocator(),
        request,
        .{},
    );
    const json_object = switch (json_value) {
        .object => |object| object,
        else => return error.InvalidMessage,
    };

    const qualified_method = try parseMethod(json_object);
    const parameters = try parseParameters(json_object);
    const options = try parseOptions(json_object);
    const last_dot = std.mem.lastIndexOfScalar(u8, qualified_method, '.') orelse
        return serializeResponse(
        response_stream,
        orgVarlinkService.InvalidParameter{ .parameter = qualified_method },
        allocator,
    );
    const interface = qualified_method[0..last_dot];
    const method = qualified_method[last_dot + 1 ..];
    inline for (@typeInfo(@TypeOf(context.*)).Struct.fields) |field| {
        if (std.mem.eql(u8, field.name, interface)) {
            try handleMethod(
                method,
                .{ .object = parameters },
                response_stream,
                arena.allocator(),
                options,
                &@field(context, field.name),
                extra_data,
            );
            return;
        }
    }
    if (std.mem.eql(u8, "org.varlink.service", interface)) {
        var varlink_service_context: VarlinkService = .{};
        try handleMethod(
            method,
            .{ .object = parameters },
            response_stream,
            arena.allocator(),
            options,
            &varlink_service_context,
            {},
        );
        return;
    }
    try serializeResponse(
        response_stream,
        orgVarlinkService.InterfaceNotFound{ .interface = interface },
        allocator,
    );
}

fn OrgVarlinkServiceImpl(comptime Context: type) type {
    return struct {
        const interface = orgVarlinkService;

        fn handleGetInfo(
            context: *@This(),
            parameters: orgVarlinkService.GetInfo.Parameters,
            response_stream: anytype,
            allocator: std.mem.Allocator,
            options: Options,
            extra_data: void,
        ) !void {
            _ = context;
            _ = parameters;
            _ = extra_data;
            if (options.oneway) {
                return;
            }
            try serializeResponse(
                response_stream,
                orgVarlinkService.GetInfo.ReturnType{
                    .vendor = Context.vendor,
                    .product = Context.product,
                    .version = Context.version,
                    .url = Context.url,
                    .interfaces = .{"org.varlink.service"} ++ std.meta.fieldNames(Context),
                },
                allocator,
            );
        }

        fn handleGetInterfaceDescription(
            context: *@This(),
            parameters: orgVarlinkService.GetInterfaceDescription.Parameters,
            response_stream: anytype,
            allocator: std.mem.Allocator,
            options: Options,
            extra_data: void,
        ) !void {
            _ = context;
            _ = extra_data;
            if (options.oneway) {
                return;
            }
            inline for (@typeInfo(Context).Struct.fields) |field| {
                if (std.mem.eql(u8, parameters.interface, field.name)) {
                    try serializeResponse(
                        response_stream,
                        orgVarlinkService.GetInterfaceDescription.ReturnType{
                            .description = field.type.interface.description,
                        },
                        allocator,
                    );
                    return;
                }
            }
            if (std.mem.eql(u8, "org.varlink.service", parameters.interface)) {
                try serializeResponse(
                    response_stream,
                    orgVarlinkService.GetInterfaceDescription.ReturnType{
                        .description = orgVarlinkService.description,
                    },
                    allocator,
                );
                return;
            }
            try serializeResponse(
                response_stream,
                orgVarlinkService.InterfaceNotFound{ .interface = parameters.interface },
                allocator,
            );
        }
    };
}
