// SPDX-FileCopyrightText: 2023 Väinö Mäkelä <vaino.makela@iki.fi>
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! JSON (de)serializing utilities

const std = @import("std");

pub fn parseParameters(map: std.json.ObjectMap) error{InvalidMessage}!std.json.ObjectMap {
    if (map.get("parameters")) |parameters_value| {
        switch (parameters_value) {
            .object => |parameters_map| {
                return parameters_map;
            },
            else => return error.InvalidMessage,
        }
    } else {
        // libvarlink accepts lacking parameters when they are expected and
        // returns the same error as if the parameters were empty. Let's
        // match this behavior.
        return std.json.ObjectMap.init(undefined);
    }
}

fn isHashMap(comptime T: type) bool {
    if (comptime @typeInfo(T) == .Struct) {
        // Custom types generated by our scanner don't have any
        // user-controllable declarations, so this should not report false
        // positives.
        return @hasDecl(T, "KV");
    }
    return false;
}

const JsonParsingError = std.mem.Allocator.Error || error{InvalidParameter};

pub fn toStruct(
    comptime T: type,
    allocator: std.mem.Allocator,
    json: std.json.Value,
    invalid_parameter: *?[]const u8,
) JsonParsingError!T {
    const struc = switch (@typeInfo(T)) {
        .Struct => |struc| struc,
        else => @compileError("Expected a struct, got: " ++ @typeName(T)),
    };
    const map: std.json.ObjectMap = blk: {
        switch (json) {
            .object => |map| break :blk map,
            else => return error.InvalidParameter,
        }
    };
    if (comptime isHashMap(T)) {
        var result: T = .{};
        var it = map.iterator();
        while (it.next()) |entry| {
            try result.putNoClobber(
                allocator,
                entry.key_ptr.*,
                try toType(
                    std.meta.fieldInfo(T.KV, .value).type,
                    allocator,
                    entry.value_ptr.*,
                ),
            );
        }
        return result;
    }
    var result: T = undefined;
    inline for (struc.fields) |field| {
        if (map.get(field.name)) |value| {
            invalid_parameter.* = field.name;
            @field(result, field.name) = try toType(
                field.type,
                allocator,
                value,
            );
        } else if (@typeInfo(field.type) == .Optional) {
            @field(result, field.name) = null;
        } else {
            invalid_parameter.* = field.name;
            return error.InvalidParameter;
        }
    }
    return result;
}

fn toType(
    comptime T: type,
    allocator: std.mem.Allocator,
    json: std.json.Value,
) JsonParsingError!T {
    if (T == std.json.Value) {
        return json;
    }
    switch (@typeInfo(T)) {
        .Bool => {
            switch (json) {
                .bool => |b| return b,
                else => return error.InvalidParameter,
            }
        },
        .Int => {
            switch (json) {
                .integer => |i| return i,
                else => return error.InvalidParameter,
            }
        },
        .Float => {
            switch (json) {
                .float => |f| return f,
                else => return error.InvalidParameter,
            }
        },
        .Pointer => |pointer| {
            if (pointer.size != .Slice) {
                @compileError("Expected a slice");
            }
            // The scanner always uses i64 as the integer type, so there is no
            // possibility of confusing strings with arrays of integers.
            if (pointer.child == u8) {
                switch (json) {
                    .string => |s| return s,
                    else => return error.InvalidParameter,
                }
            } else {
                switch (json) {
                    .array => |arr| {
                        // Exact memory management is not needed here as we are
                        // using an arena allocator.
                        const result = try allocator.alloc(pointer.child, arr.items.len);
                        for (arr.items, 0..) |item, i| {
                            result[i] = try toType(
                                pointer.child,
                                allocator,
                                item,
                            );
                        }
                        return result;
                    },
                    else => return error.InvalidParameter,
                }
            }
        },
        .Optional => |optional| {
            switch (json) {
                .null => return null,
                else => return try toType(
                    optional.child,
                    allocator,
                    json,
                ),
            }
        },
        .Struct => {
            var dummy_invalid_parameter: ?[]const u8 = null;
            return toStruct(T, allocator, json, &dummy_invalid_parameter);
        },
        .Enum => {
            switch (json) {
                .string => |str| return std.meta.stringToEnum(T, str) orelse error.InvalidParameter,
                else => return error.InvalidParameter,
            }
        },
        else => @compileError("Unsupported type: " ++ @typeName(T)),
    }
}

/// Serialize value to std.json.Value. This method does free memory on
/// allocation errors or provide a way to free the allocated memory, so it's
/// recommended to use it with an arena allocator.
pub fn jsonize(value: anytype, allocator: std.mem.Allocator) std.mem.Allocator.Error!std.json.Value {
    const T = @TypeOf(value);
    if (T == std.json.Value) {
        return value;
    }
    if (comptime isHashMap(T)) {
        var result = std.StringArrayHashMap(std.json.Value).init(allocator);
        var it = value.iterator();
        while (it.next()) |entry| {
            try result.putNoClobber(
                entry.key_ptr.*,
                try jsonize(entry.value_ptr.*, allocator),
            );
        }
        return .{ .object = result };
    }
    switch (@typeInfo(T)) {
        .Bool => return .{ .bool = value },
        .Int => return .{ .integer = value },
        .Float => return .{ .float = value },
        .Pointer => |pointer| {
            if (pointer.size == .One) {
                // TODO: Custom compile error for non-string?
                return .{ .string = value };
            }
            if (pointer.size != .Slice) {
                @compileError("Many-item and C pointers are not supported");
            }
            if (pointer.child == u8) {
                return .{ .string = value };
            } else {
                var arr = try std.ArrayList(std.json.Value).initCapacity(
                    allocator,
                    value.len,
                );
                for (value) |element| {
                    arr.appendAssumeCapacity(try jsonize(element, allocator));
                }
                return .{ .array = arr };
            }
        },
        .Optional => {
            if (value) |child| {
                return jsonize(child, allocator);
            } else {
                return .null;
            }
        },
        .Struct => |struc| {
            var result = std.StringArrayHashMap(std.json.Value).init(allocator);
            inline for (struc.fields) |field| {
                try result.putNoClobber(
                    field.name,
                    try jsonize(@field(value, field.name), allocator),
                );
            }
            return .{ .object = result };
        },
        .Enum => return .{ .string = @tagName(value) },
        else => @compileError("Unsupported type: " ++ @typeName(T)),
    }
}

pub fn write(stream: anytype, json: std.json.Value) !void {
    var write_stream = std.json.writeStream(stream, .{});
    try json.jsonStringify(&write_stream);
}

/// Check that the provided type is a valid JsonWriter.
pub fn checkJsonWriter(comptime JsonWriter: type) void {
    if (!@hasDecl(JsonWriter, "writeJson")) {
        @compileError("JsonWriter is missing the writeJson function");
    }
    const writer = @field(JsonWriter, "writeJson");
    switch (@typeInfo(@TypeOf(writer))) {
        .Fn => |_| {},
        else => @compileError("JsonWriter.writeJson is not a function"),
    }
}

/// A JsonWriter that adds a trailing zero byte after each sent message.
pub fn TrailingZeroWriter(comptime Writer: type) type {
    return struct {
        writer: Writer,

        // TODO: Have something that doesn't require an allocation?
        pub fn writeJson(context: *@This(), json: std.json.Value) Writer.Error!void {
            try write(context.writer, json);
            try context.writer.writeByte(0);
        }
    };
}

/// Return a new TrailingZeroWriter with the given underlying writer.
pub fn trailingZeroWriter(writer: anytype) TrailingZeroWriter(@TypeOf(writer)) {
    return .{ .writer = writer };
}
